"""markdown on Post.content_html

Revision ID: 51b210ba922e
Revises: 4bc48ba2e4ea
Create Date: 2016-12-30 19:44:37.408698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b210ba922e'
down_revision = '4bc48ba2e4ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'content_html')
    # ### end Alembic commands ###
